#!/bin/bash

#Given a list of folder names for organisms (e.g. burdorferi, garinii, etc.) as command line arguments, this script
#finds genes in the intersection of the unique gene lists of those organisms.

touch core.txt
touch temp.txt
cat "$1""/""$1""_unique_gene_list.txt" > core.txt
for var in "$@"
do
	cat "$var""/""$var""_unique_gene_list.txt" > currFile.txt
	cp core.txt temp.txt
	comm -12 temp.txt currFile.txt > core.txt
done

rm temp.txt currFile.txt
